routes:
  - method: GET
    path: /users/:id
    response:
      - name: Warm up
        cond: routeRequestCount < 2
        status: 500
        header:
          Content-Type: application/json
        body: >
          {
            "message": "Warn up now.... Please wait."
          }
      - name: 200
        cond: param["id"] < 100
        delay: 0.0
        status: 200
        header:
          Content-Type: application/json
        body: >
          {
            "id": {{ .Param.id }},
            "name": "Alice"
          }
      - name: 404
        status: 404
        header:
          Content-Type: application/json
        body: >
          {
            "message": "Not Found"
          }
  - method: POST
    path: /users
    response:
      - name: 401
        cond: true
        status: 401
        header:
          Content-Type: application/json
        body: >
          {
            "message": "Unauthorized"
          }
  - method: "*"
    path: /company
    response:
      - name: search
        status: 302
        redirect: https://soranoba.net
  - method: "*"
    path: "*"
    response:
      - name: default
        status: 404
        header:
          Content-Type: application/json
        body: >
          {
            "message": "Not Found"
          }
